from .material_transfer import MaterialTransferController
from .purchase_receipt import PurchaseReceiptController


get_warehouse = MaterialTransferController.get_user_current_warehouse
get_material_request_fields = MaterialTransferController.get_material_request_fields
update_material_request_status = MaterialTransferController.update_material_request_status
get_request_from_picklist = MaterialTransferController.get_request_from_picklist
get_items_sold = MaterialTransferController.get_items_sold_over_the_last_two_weeks

get_po_pending_approval = MaterialTransferController.get_po_pending_approval
get_items_in_warehouse = MaterialTransferController.get_all_items_in_users_warehouse
generate_material_request = MaterialTransferController.generate_material_request
generate_material_request_dental = MaterialTransferController.generate_request_for_user_branch_dental
generate_material_request_surgicals = MaterialTransferController.generate_request_for_user_branch_nondrugs
get_requisition_pending = MaterialTransferController.get_requisition_pending
create_purchase_order = MaterialTransferController.create_purchase_order
get_all_items_sold_in_branch = MaterialTransferController.get_all_items_sold_in_branch
get_items_to_buy_in_warehouse = MaterialTransferController.get_items_to_buy_in_warehouse

task = MaterialTransferController.task
tasks = MaterialTransferController.tasks
default_company = MaterialTransferController.default_company

update_purchase_order = MaterialTransferController.update_purchase_order
get_all_pos = MaterialTransferController.get_all_pos
get_user_requisition_requests = MaterialTransferController.get_user_requisition_requests
generate_request_for_user_branch = MaterialTransferController.generate_request_for_user_branch
get_approved_po = MaterialTransferController.get_approved_po
get_my_pos = MaterialTransferController.get_my_pos
generate_po_branch = MaterialTransferController.generate_po_branch
get_requisition_pending_my_action = MaterialTransferController.get_requisition_pending_my_action
get_item_defaults = MaterialTransferController.get_item_defaults
get_to_be_received_per_branch = MaterialTransferController.get_to_be_received_per_branch
get_po_pending_review = MaterialTransferController.get_po_pending_review
render_orders = MaterialTransferController.render_orders_by_date
render_orders_branch = MaterialTransferController.render_orders_by_branch
render_orders_by_supplier = MaterialTransferController.render_orders_by_supplier
supllier_dets = MaterialTransferController.supllier_dets
notify_queue_purchase_order = MaterialTransferController.notify_queue_purchase_order
reject_purchase_order_with_comment = MaterialTransferController.reject_purchase_order_with_comment
return_for_review = MaterialTransferController.return_for_review
approve_purchase_order = MaterialTransferController.approve_purchase_order
all_requests = MaterialTransferController.all_requests
get_ordered_qty_from_purchase_order = MaterialTransferController.get_ordered_qty_from_purchase_order
approve_purchase_order_with_comment = MaterialTransferController.approve_purchase_order_with_comment
render_orders_by_po_number = MaterialTransferController.render_orders_by_po_number
set_global_warehouse = MaterialTransferController.set_global_warehouse
cancel_transfer_request = MaterialTransferController.cancel_transfer_request

# Extra Stock Declaration
get_branch_and_warehouse = MaterialTransferController.get_branch_and_warehouse
validate_item_on_excess_stock = MaterialTransferController.validate_item_on_excess_stock
# inititate_goods_transfer = MaterialTransferController.inititate_goods_transfer
get_available_in_other_warehouses = PurchaseReceiptController.get_available_in_other_warehouses
create_material_transfer_request = PurchaseReceiptController.create_material_transfer_request
get_my_goods_transfer_requests = PurchaseReceiptController.get_my_goods_transfer_requests
approve_stock_transfer = PurchaseReceiptController.approve_stock_transfer
decline_stock_transfer = PurchaseReceiptController.decline_stock_transfer
receive_stock = PurchaseReceiptController.receive_stock
get_user_branch_and_warehouse = PurchaseReceiptController.get_user_branch_and_warehouse


# Test endpoint
test = MaterialTransferController.get_warehouse_from_online_branch


# Purchase Receipts
validate_purchase_receipt = PurchaseReceiptController.validate_purchase_receipt
get_purchase_receipt_items = PurchaseReceiptController.get_purchase_receipt_items
save_batch = PurchaseReceiptController.create_batch_number
save_purchase_receipt_item = PurchaseReceiptController.save_purchase_receipt_item
create_new_purchase_receipt_item = PurchaseReceiptController.create_new_purchase_receipt_item
get_purchase_order_quantity = PurchaseReceiptController.get_purchase_order_quantity
update_receipt_status = PurchaseReceiptController.update_receipt_status
mark_po_as_sent_to_supplier = PurchaseReceiptController.mark_po_as_sent_to_supplier
update_batch_details = PurchaseReceiptController.update_batch_details
remove_item_from_receipt = PurchaseReceiptController.remove_item_from_receipt
save_batch_on_purchase_receipt_items  = PurchaseReceiptController.save_batch_on_purchase_receipt_items


get_company_details = PurchaseReceiptController.get_company_details
auto_select_batch_qty = PurchaseReceiptController.auto_select_batch_required_to_fulfill_transfer