from .medical_orders import MedicalOrderController
from .inpatient_billing import invoice_inpatient_record_items,add_tests_to_invoice, bill_package
from .utlis.inpatient_record_utils import InpatientRecordUtils
from .inpatient_billing import InpatientBillingController



generate_medical_order = MedicalOrderController.generate_medical_order
get_patient_information = MedicalOrderController.get_patient_information
test_medication_order = MedicalOrderController.test_medication_order
get_inpatient_prescription = MedicalOrderController.get_inpatient_prescription
get_medical_order_list = MedicalOrderController.get_medical_order_list
create_prescrption_schedule = MedicalOrderController.create_prescrption_schedule
get_scroll_table_data = MedicalOrderController.get_scroll_table_data
get_filtered_scroll_table_data = MedicalOrderController.get_filtered_scroll_table_data
administer_with_comment = MedicalOrderController.administer_with_comment
administer_without_comment = MedicalOrderController.administer_without_comment
update_prescription = MedicalOrderController.partial_update_prescription_table
update_prescription_table = MedicalOrderController.update_prescription_table
set_total_cost = MedicalOrderController.update_billed_quantity_total_price
check_multidisciplinary_status = MedicalOrderController.check_multidisciplinary_status
mark_prescription_as_patient_owned = (
    MedicalOrderController.mark_prescription_as_patient_owned
)
create_prescription_schedule = MedicalOrderController.create_prescription_schedule
stop_medication = MedicalOrderController.stop_medication
get_stopped_meds_list = MedicalOrderController.get_stopped_meds_list
receive_meds_and_create_schedule = (
    MedicalOrderController.receive_meds_and_create_schedule
)
reopen_slot = MedicalOrderController.reopen_slot
dispense_medications = MedicalOrderController.dispense_medications
dispense_with_presc_number = MedicalOrderController.dispense_with_presc_number
second_approval_high_alert_medication = MedicalOrderController.second_approval_high_alert_medication
get_discharge_medication_list = MedicalOrderController.get_discharge_medication_list
get_get_user_list = MedicalOrderController.get_get_user_list
create_procedure_tests = MedicalOrderController.create_procedure_tests
get_inpatient_record_procedures = MedicalOrderController.get_inpatient_record_procedures
get_medication_list = MedicalOrderController.get_medication_list
add_verbal_order = MedicalOrderController.add_verbal_order
get_bincard_data = MedicalOrderController.get_bincard_data
return_item = MedicalOrderController.return_item
initiate_returns = MedicalOrderController.initiate_returns

create_prescription = InpatientBillingController.create_prescription

# Dsicharges
initiate_discharge = MedicalOrderController.initiate_discharge

# Billing
invoice_inpatient_record_items = invoice_inpatient_record_items
add_tests_to_invoice = add_tests_to_invoice
add_lab_test_to_invoice = MedicalOrderController.add_lab_test_to_invoice
get_sales_invoice = InpatientBillingController.get_sales_invoice
 
test = MedicalOrderController.test_medication_order()


get_current_primary_nurse = InpatientRecordUtils.get_current_primary_nurse
set_current_primary_nurse = InpatientRecordUtils.set_current_primary_nurse
get_receiving_nurse = InpatientRecordUtils.get_receiving_nurse
 
pharmacy_queue = MedicalOrderController.pharmacy_queue
update_prescription_details = MedicalOrderController.update_prescription_details
high_alerts = MedicalOrderController.high_alerts
new_and_repeat_medication = MedicalOrderController.new_and_repeat_medication
discharge_medication = MedicalOrderController.discharge_medication

get_items = InpatientBillingController.get_billable_items
add_to_bill = InpatientBillingController.add_to_bill
items_in_bill = InpatientBillingController.items_in_bill
bill_package = bill_package

fetch_item_groups = InpatientBillingController.fetch_item_groups
fetch_item_by_groups = InpatientBillingController.fetch_item_by_groups
get_item_details = InpatientBillingController.get_item_details
get_patient_in_invoice = InpatientBillingController.get_patient_in_invoice
search_items = InpatientBillingController.search_items
fetch_doctors = InpatientBillingController.fetch_doctors



# Inpatient returns
inpatient_returns = MedicalOrderController.inpatient_returns
return_ip_items = MedicalOrderController.return_ip_items

# Testing end point
test_stuff = MedicalOrderController.test


 
