import requests
from requests.auth import HTTPBasicAuth
import json
import base64
import datetime
import frappe


class Mpesa:
    def __init__(self, consumer_key, consumer_secret, callback_url, business_shortcode, till_number, passcode, is_live):
        """
        Initialization of the Mpesa Services

        Cousumer Key and Consumer Secret are found on your Client Dashboard
        https://developer.safaricom.co.ke/user/me/apps

        consumer_key: "<STRING>",
        consumer_secret: "<STRING>",

        Passkey , Business Shortcode and Shortcode are found on the Test Credentials Page
        https://developer.safaricom.co.ke/test_credentials

        passkey: "<STRING>", // bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
        BusinessShortCode: "<INTEGER>", // 174379
        ShortCode: "<INTEGER>", //600000

        Secruity Credentials is generated by adding the consumer secret as
        the Initiator Security Password and clicking Generate Credentials

        SecurityCredential: "<STRING>", //Safaricom147!
        Initiator: "<STRING>", //testapi

        callBackBaseUrl: "<STRING>",

        is_live: True / False

        """
        self._auth_token = ""
        self._consumer_key = consumer_key
        self._consumer_secret = consumer_secret
        self._callback_url = callback_url
        self.business_shortcode = business_shortcode
        self.till_number = till_number
        self.passcode = passcode
        self.is_live = is_live
        self.subdomain = "sandbox"
        if (is_live):
            self.subdomain = "api"
        self._accountBalance_url = "https://{0}.safaricom.co.ke/mpesa/accountbalance/v1/query".format(
            self.subdomain)
        self._auth_url = "https://{0}.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials".format(
            self.subdomain)
        self._stk_url = 'https://{0}.safaricom.co.ke/mpesa/stkpush/v1/processrequest'.format(
            self.subdomain)
        self._stkCheck_url = 'https://{0}.safaricom.co.ke/mpesa/stkpushquery/v1/query'.format(
            self.subdomain)
        self._c2bRegister_url = "https://{0}.safaricom.co.ke/mpesa/c2b/v1/registerurl".format(
            self.subdomain)
        self._c2bSimulate_url = " https://{0}.safaricom.co.ke/mpesa/c2b/v1/simulate".format(
            self.subdomain)
        self._b2c_url = "https://{0}.safaricom.co.ke/mpesa/b2c/v1/paymentrequest".format(
            self.subdomain)
        self._transaction_status_url = "https://{0}.safaricom.co.ke/mpesa/transactionstatus/v1/query".format(
            self.subdomain)

    def _getAuthToken(self) -> str:
        print("Authing")

        try:

            auth = HTTPBasicAuth(self._consumer_key,
                                 self._consumer_secret)

            response = requests.get(self._auth_url, auth=auth)

            dictionary_response = json.loads(response.text)

            print(dictionary_response)

            self._auth_token = dictionary_response["access_token"]
            return dictionary_response["access_token"]
        except Exception as e:
            print("Auth Error")
            print(e)
            frappe.log_error(e, "MPESA AUTH ERROR  /mpesa/mpesa.py")
            return ""

    def _generateTimeStamp(self):

        time = str(datetime.datetime.now()).split(".")[0].replace(
            "-", "").replace(" ", "").replace(":", "")

        return time

    def _generatePassword(self, timestamp, shortcode):
        password = shortcode+self.passcode+timestamp
        online_password = base64.b64encode(password.encode())
        decode_password = online_password.decode('utf-8')

        return decode_password

    def _addHeaders(self):

        _access_token = self._auth_token
        headers = {"Authorization": "Bearer %s" % _access_token}

        print(headers)

        return headers

    def stkPush(self, phone, amount,  AccountReference, TransactionDesc):
        """
        Use this API to check the status of a Lipa Na M-Pesa Online Payment.

        Request Body
        {
        "BusinessShortCode":"174379",
        "Password": "MTc0Mzc5YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOTIwMTYwMjE2MTY1NjI3",
        "Timestamp":"20160216165627",
        "TransactionType": "CustomerPayBillOnline",
        "Amount":"1",
        "PartyA":"254708374149",
        "PartyB":"174379",
        "PhoneNumber":"254708374149",
        "CallBackURL":"https://mydomain.com/pat",
        "AccountReference":"Test",
        "TransactionDesc":"Test"
        }

        Response Body
        {
        "ResponseCode": "0",
        "ResponseDescription":"The service request has been accepted successsfully",
        "MerchantRequestID":"22205-34066-1",
        "CheckoutRequestID":"ws_CO_13012021093521236557",
        "ResultCode": "0",
        "ResultDesc":"The service request is processed successfully."
        }


        """

        headers = self._addHeaders()
        BusinessShortCode = self.business_shortcode
        PartyB = self.till_number
        timestamp = self._generateTimeStamp()
        password = self._generatePassword(timestamp, BusinessShortCode)

        jsonBody = {
            "BusinessShortCode": BusinessShortCode,
            "Password": password,
            "Timestamp": timestamp,
            "TransactionType": "CustomerPayBillOnline",
            "Amount": amount,
            "PartyA": phone,
            "PartyB": PartyB,
            "PhoneNumber": phone,
            "CallBackURL": self._callback_url,
            "AccountReference": AccountReference,
            "TransactionDesc": TransactionDesc
        }
        print(jsonBody)

        response = requests.post(self._stk_url, json=jsonBody, headers=headers)
        dictionary_response = json.loads(response.text)
        print(dictionary_response)
        return dictionary_response

    def stkCheck(self, CheckoutRequestID):
        """


        """

        headers = self._addHeaders()
        BusinessShortCode = self.business_shortcode
        timestamp = self._generateTimeStamp()
        password = self._generatePassword(timestamp, BusinessShortCode)
        jsonBody = {
            "BusinessShortCode": BusinessShortCode,
            "Password": password,
            "Timestamp": timestamp,
            "CheckoutRequestID": CheckoutRequestID

        }
        response = requests.post(
            self._stkCheck_url, json=jsonBody, headers=headers)

        dictionary_response = json.loads(response.text)
        print(dictionary_response)
        return dictionary_response

    def c2bRegister(self, ConfirmationURL, ValidationURL, ResponseType, ShortCode):
        """
        Register validation and confirmation URLs on M-Pesa

        Request Body
        {
        "ShortCode": "600610",
        "ResponseType": "[Cancelled/Completed]",
        "ConfirmationURL": "[confirmation URL]",
        "ValidationURL": "[validation URL]"
        }

        Response Body
        {
        "OriginatorCoversationID": "60682-3118069-1",
        "ResponseCode": "0",
        "ResponseDescription": "success"
        }

        """
        headers = self._addHeaders()
        print(headers)
        jsonBody = {
            "ConfirmationURL": ConfirmationURL,
            "ValidationURL": ValidationURL,
            "ResponseType": ResponseType,
            "ShortCode": ShortCode
        }
        print(jsonBody)

        response = requests.get(self._c2bRegister_url,
                                json=jsonBody, headers=headers)
        dictionary_response = json.loads(response.text)
        print(dictionary_response)

        return dictionary_response

    def c2bTransact(self, ShortCode, CommandID, Amount, Msisdn, BillRefNumber):
        """
        The below request body captures minimal details to simulates the journey a customer goes through when making a payment from Sim Tool Kit or Safaricom APP.

        Request Body
        {
        "ShortCode":"600247"
        "Command ID": "CustomerPayBillOnline",
        "Amount":"10",
        "Msisdn":"254708374149",
        "BillRefNumber":"00000",
        }

        Response Body
        {
        "ConversationID": "AG_20191219_000043fdf61864fe9ff5",
        "OriginatorCoversationID": "16738-27456357-1",
        "ResponseDescription": "Accept the service request successfully."
        }
        """

        headers = self._addHeaders()
        jsonBody = {
            "ShortCode": ShortCode,
            "CommandID": CommandID,
            "Amount": Amount,
            "Msisdn": Msisdn,
            "BillRefNumber": BillRefNumber
        }

        response = requests.post(
            self._c2bSimulate_url, json=jsonBody, headers=headers)
        dictionary_response = json.loads(response.text)
        print(dictionary_response)
        return dictionary_response

    def confimMpesa(self):
        """
        The below request body captures minimal details to simulates the journey a customer goes through when making a payment from Sim Tool Kit or Safaricom APP.

        Request Body
        {    
        "ShortCode":"600247"
        "Command ID": "CustomerPayBillOnline",
        "Amount":"10",
        "Msisdn":"254708374149",
        "BillRefNumber":"00000",
        }

        {
      "Initiator": "testapiuser",
      "SecurityCredential": "*********************",
      "CommandID": "TransactionStatusQuery",
      "TransactionID": "NEF61H8J60",
       "OriginalConcersationID": "AG_20190826_0000777ab7d848b9e721",
      "PartyA": "600782",
      "IdentifierType": "4",
      "ResultURL": "http://myservice:8080/transactionstatus/result",
      "QueueTimeOutURL": "http://myservice:8080/timeout",
      "Remarks": "OK",
      "Occasion": "OK"
        }

        Response Body
        {
        "ConversationID": "AG_20191219_000043fdf61864fe9ff5",
        "OriginatorCoversationID": "16738-27456357-1",
        "ResponseDescription": "Accept the service request successfully."
        }
        """

        headers = self._addHeaders()
        jsonBody = {
            "Initiator": "testapiuser",
            "SecurityCredential": "CVHRAqrcISnf+7zy1FFTCwjS5BVFSFJbXHV7UMZHUSl/ktqrs1lkaLjk/Az1m7nDiXMv95rDICb7eAvLGJBNYJEAEmVwxi/bNzsmVALvI4l9QUEd8wrVf99Q43aK6r1zuG+9TWLcJKiLe+kdMOtxpfRoocgmbvfnG5oSkWTMFrGFZgiddBN31TBvc/lI1JMYSIwCcR1SeKV2JFojb244tiHJJcdeV7c3i5mLwVA5ru4G4etFpDVq8yNhQo1COaHFIKcoWuDOcTG2Oo8ZzdET9IZiQsO38PCHGlRaOUmVD6TJqqDncdNE+eNy2DewMxvs4aJidwRJbc/TbD+5C+WPZw==",
            "CommandID": "TransactionStatusQuery",
            "TransactionID": "NEF61H8J60",
            "OriginalConcersationID": "AG_20190826_0000777ab7d848b9e721",
            "PartyA": "600782",
            "IdentifierType": "4",
            "ResultURL": "https://0ec5-41-191-228-6.ngrok.io/transactionstatus/result",
            "QueueTimeOutURL": "https://0ec5-41-191-228-6.ngrok.io/transactionstatus/timeout",
            "Remarks": "OK",
            "Occasion": "OK"
        }

        response = requests.get(
            "https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query", json=jsonBody, headers=headers)
        dictionary_response = json.loads(response.text)
        print(dictionary_response)
        return dictionary_response

    def checkTransactionStatus(self, Initiator: str, SecurityCredential: str, TransactionID: str, PartyA: int, ResultURL: str, QueueTimeOutURL: str, IdentifierType: str = "1", CommandID: str = "TransactionStatusQuery", Remarks: str = "", Occasion: str = ""):
        """
        Check the status of a transaction

        Request Body
        {
        "Initiator": "",
        "SecurityCredential": "",
        "TransactionID": "",
        "PartyA": "",
        "ResultURL": "",
        "QueueTimeOutURL": "",
        "IdentifierType": "1",
        "CommandID": "TransactionStatusQuery",
        "Remarks": " ",
        "Occasion": " "
        }
        """
        headers = self._addHeaders()
        jsonBody = {
            "Initiator": Initiator,
            "SecurityCredential": SecurityCredential,
            "CommandID": CommandID,
            "TransactionID": TransactionID,
            "PartyA": PartyA,
            "IdentifierType": IdentifierType,
            "ResultURL": ResultURL,
            "QueueTimeOutURL": QueueTimeOutURL,
            "Remarks": Remarks,
            "Occasion": Occasion
        }

        response = requests.post(
            self._transaction_status_url, json=jsonBody, headers=headers)
        dictionary_response = json.loads(response.text)
        print(dictionary_response)
        return dictionary_response
